# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fb6cd3bfbed9d7c7e2f4748e63b2fb30a251fa3e86357607e973c9e71384183ef215b83d70e6b2933db5b87de90f81e6f01f9e218c5e6ed216be46d6975ff7ea
  stripe_public_key: <%= ENV["STRIPE_PUBLISHABLE_KEY_DEV"] %>
  stripe_secret_key: <%= ENV["STRIPE_SECRET_KEY_DEV"] %>
  stripe_webhook_secret: <%= ENV["STRIPE_WEBHOOK_SECRET"] %>
  stripe_signing_secret: <%= ENV["STRIPE_SIGNING_SECRET"] %>

test:
  secret_key_base: d686785651be6326f2b77fa501acf517e252a2024c16dc7d4a7b273d26fd9d6f587bf801dad4c6569aae899668dfdbc88d55072cc4cac9b505c442e17c5a102c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
